### ISSUE TITLE
TableCell short text

### ISSUE THREAD

**Issue by kevinvenclovas** [skclusive/Skclusive.Material.Component#86]
Is there a solution to short a text in a tabelcell with ... if the text is to long?

![image](https://user-images.githubusercontent.com/7681603/103129384-dfe17480-4698-11eb-91c9-55ad3720a57a.png)

i want only a single line in the tablecell

**Comment by skclusive** [comment]
this could be achieved using css. below class could be passed to the `<TableCell Class="truncate' />`

https://daily-dev-tips.com/posts/css-truncate-text-with-ellipsis/

```css
.truncate {
  width: 200px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
